import "./Home.css";

import React from "react";

export const Home = () => {
  return (
    <>
      <div className="form-wrap">
        <div className="form">
          <img
            className="header-img"
            src="https://www.fotor.com/blog/wp-content/uploads/2017/09/1-2.jpg"
            // src="https://images.template.net/wp-content/uploads/2016/01/Car-Wash-Roll-Up-Banner-Template.jpg"
          />
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
          <p>Home</p>
        </div>
      </div>
    </>
  );
};
